# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_collector.ui'
#
# Created: Sun Nov 10 21:09:18 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(433, 477)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.qlist = QtGui.QListView(self.centralwidget)
        self.qlist.setGeometry(QtCore.QRect(90, 70, 256, 301))
        self.qlist.setObjectName(_fromUtf8("qlist"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.err_lbl = QtGui.QLabel(self.centralwidget)
        self.err_lbl.setGeometry(QtCore.QRect(20, 240, 381, 71))
        self.err_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.err_lbl.setObjectName(_fromUtf8("err_lbl"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(90, 170, 262, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.a = QtGui.QLineEdit(self.splitter)
        self.a.setObjectName(_fromUtf8("a"))
        self.lbl = QtGui.QLabel(self.splitter)
        self.lbl.setObjectName(_fromUtf8("lbl"))
        self.b = QtGui.QLineEdit(self.splitter)
        self.b.setObjectName(_fromUtf8("b"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 391, 351))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.plotBtn = QtGui.QPushButton(self.centralwidget)
        self.plotBtn.setGeometry(QtCore.QRect(170, 380, 85, 27))
        font = QtGui.QFont()
        font.setBold(True)
        self.textEdit.setFont(font)
        self.plotBtn.setObjectName(_fromUtf8("plotBtn"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):# to set the name and other features.
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "VPoSD", None, QtGui.QApplication.UnicodeUTF8))#To print the name of VPoSD on Main window 
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.err_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl.setText(QtGui.QApplication.translate("VPoSD", "x 10 ^", None, QtGui.QApplication.UnicodeUTF8))
        self.plotBtn.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_collector.ui'
#
# Created: Tue Nov 19 22:09:46 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(629, 684)
        font = QtGui.QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.qlist = QtGui.QListView(self.centralwidget)
        self.qlist.setGeometry(QtCore.QRect(150, 170, 341, 301))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.qlist.setFont(font)
        self.qlist.setObjectName(_fromUtf8("qlist"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.err_lbl = QtGui.QLabel(self.centralwidget)
        self.err_lbl.setGeometry(QtCore.QRect(30, 270, 561, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.err_lbl.sizePolicy().hasHeightForWidth())
        self.err_lbl.setSizePolicy(sizePolicy)
        self.err_lbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.err_lbl.setFont(font)
        self.err_lbl.setLineWidth(2)
        self.err_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.err_lbl.setObjectName(_fromUtf8("err_lbl"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(180, 200, 262, 27))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.a = QtGui.QLineEdit(self.splitter)
        self.a.setObjectName(_fromUtf8("a"))
        self.lbl = QtGui.QLabel(self.splitter)
        self.lbl.setObjectName(_fromUtf8("lbl"))
        self.b = QtGui.QLineEdit(self.splitter)
        self.b.setObjectName(_fromUtf8("b"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 581, 451))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.plotBtn = QtGui.QPushButton(self.centralwidget)
        self.plotBtn.setGeometry(QtCore.QRect(280, 500, 85, 27))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.plotBtn.setFont(font)
        self.plotBtn.setObjectName(_fromUtf8("plotBtn"))
        self.Name = QtGui.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(10, 610, 101, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Name.sizePolicy().hasHeightForWidth())
        self.Name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.Name.setFont(font)
        self.Name.setMouseTracking(True)
        self.Name.setTextFormat(QtCore.Qt.RichText)
        self.Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.GuidedBy = QtGui.QLabel(self.centralwidget)
        self.GuidedBy.setGeometry(QtCore.QRect(440, 590, 91, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.GuidedBy.setFont(font)
        self.GuidedBy.setObjectName(_fromUtf8("GuidedBy"))
        self.Name_R_Sir = QtGui.QLabel(self.centralwidget)
        self.Name_R_Sir.setGeometry(QtCore.QRect(440, 600, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.Name_R_Sir.setFont(font)
        self.Name_R_Sir.setObjectName(_fromUtf8("Name_R_Sir"))
        self.Roll_No = QtGui.QLabel(self.centralwidget)
        self.Roll_No.setGeometry(QtCore.QRect(10, 630, 71, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Roll_No.setFont(font)
        self.Roll_No.setObjectName(_fromUtf8("Roll_No"))
        self.ECED = QtGui.QLabel(self.centralwidget)
        self.ECED.setGeometry(QtCore.QRect(10, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.ECED.setFont(font)
        self.ECED.setObjectName(_fromUtf8("ECED"))
        self.NITC = QtGui.QLabel(self.centralwidget)
        self.NITC.setGeometry(QtCore.QRect(560, 0, 61, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.NITC.setFont(font)
        self.NITC.setObjectName(_fromUtf8("NITC"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 109, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "VPoSD", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.err_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl.setText(QtGui.QApplication.translate("MainWindow", "x 10 ^", None, QtGui.QApplication.UnicodeUTF8))
        self.plotBtn.setText(QtGui.QApplication.translate("MainWindow", "PLOT", None, QtGui.QApplication.UnicodeUTF8))
        self.Name.setText(QtGui.QApplication.translate("MainWindow", "Ajai V Babu", None, QtGui.QApplication.UnicodeUTF8))
        self.GuidedBy.setText(QtGui.QApplication.translate("MainWindow", "Guided By", None, QtGui.QApplication.UnicodeUTF8))
        self.Name_R_Sir.setText(QtGui.QApplication.translate("MainWindow", "Dr. Rama S Komaragiri", None, QtGui.QApplication.UnicodeUTF8))
        self.Roll_No.setText(QtGui.QApplication.translate("MainWindow", "M120231EC", None, QtGui.QApplication.UnicodeUTF8))
        self.ECED.setText(QtGui.QApplication.translate("MainWindow", "ECED", None, QtGui.QApplication.UnicodeUTF8))
        self.NITC.setText(QtGui.QApplication.translate("MainWindow", "NIT Calicut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", " ", None, QtGui.QApplication.UnicodeUTF8))

